name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.m2/wrapper
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', 'mvnw*', '.mvnw') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build and quick tests
      run: ./mvnw --batch-mode --no-transfer-progress package
    - name: Slow tests
      run: ./mvnw --batch-mode --no-transfer-progress verify
